### ISSUE TITLE
Upnext 2.0.6+dev.0+matrix not working

### ISSUE THREAD

**Issue by fl380** [MoojMidge/service.upnext#12]
Hello, I'm using the above version on Kodi 19.4 with the Jellyfin for Kodi addon. Unfortunately the upnext popup doesn't appear. Here's the log which hopefully will help identify the problem. Pre v2 versions did work.

[kodilog.txt](https://github.com/MoojMidge/service.upnext/files/10175296/kodilog.txt)

**Comment by MoojMidge** [comment]
The link to the log doesn't work - it looks to be set for private access only.

**Comment by fl380** [comment]
> The link to the log doesn't work - it looks to be set for private access only.

Apologies, it seems to be pending moderation. I'll confirm when approved or post it somewhere else

**Comment by MoojMidge** [comment]
All good. If there is a problem you can just upload it to Github when you post a comment or issue

**Comment by MoojMidge** [comment]
The Jellyfin addon appears to be sending the firstaired info as an integer year rather than a date string, which generates an error when trying to parse the date.

Pushed a fix in UpNext, you can download from master and see if it works.

**Comment by fl380** [comment]
> The Jellyfin addon appears to be sending the firstaired info as an integer year rather than a date string, which generates an error when trying to parse the date.
> 
> Pushed a fix in UpNext, you can download from master and see if it works.

Thanks, unfortunately the popup still doesn't appear, here's a new log
[kodi.log](https://github.com/MoojMidge/service.upnext/files/10179673/kodi.log)

**Comment by MoojMidge** [comment]
Made some changes to the expected structure of data that plugins send to UpNext. It was meant to be a backwards compatible change, but I missed one spot.

Try master again.
