### ISSUE TITLE
Issue trying to install addon from zipfile

### ISSUE THREAD

**Issue by classicspam** [MoojMidge/service.upnext#19]
I am having issues that the addon will not install from a zipfile and give a python dependency error:

Log Message:

2023-03-30 23:05:13.166 T:16849   error <general>: CAddonInstallJob[service.upnext]: The dependency on xbmc.python version 2.25.0 could not be satisfied.

Currently Kodi is installed on an nvidia shield (I believe the 2017 version)

- package version:  service.upnext-2.0.20-dev.0.zip
- Kodi version: 20.1.0 Git 20230312-289ec664e3
- Operating system Version: Android TV 11.0.0 API level 30 (kernel: Linux 4.9.141-tegra-gfad87a91fd8a)

I am not sure if this is an issue with my setup in particular or if it is a bug...

**Comment by MoojMidge** [comment]
You are trying to install the Kodi 18 version which is not compatible with Kodi 19+

If you download the unmodified code directly then that should work on Kodi 18+, but if you download a release then you need the correct zip file for the version of Kodi that you are using. In this instance you will need the zip file that has `matrix` in the filename for Kodi 19+

Try [service.upnext-2.0.20+dev.0+matrix.1.zip](https://github.com/MoojMidge/service.upnext/releases/download/v2.0.20%2Bdev.0/service.upnext-2.0.20+dev.0+matrix.1.zip)

**Comment by MoojMidge** [comment]
There are a bunch of issues with Jellyfin not storing correct data in the Kodi library. Issues #12 and #14 are probably related, but some additional workarounds may be required for the widgets. Unfortunately not only is the firstaired date format wrong, it also appears to change formats when Jellyfin does a library update to update resume points and play counts.

If you can get some details of what the last played airdate is, along with the next episode air date, should be able to work something out.
