### ISSUE TITLE
Widgets not showing up

### ISSUE THREAD

**Issue by Lefo16** [MoojMidge/service.upnext#20]
Hi,

Installed latest Kodi 20.2 with this fork of UpNext and the UpNext Movies and UpNext Episodes is blank.

How to fix?

Version: service.upnext-2.0.25+dev.0+matrix.1.zip

![image](https://github.com/MoojMidge/service.upnext/assets/143577835/51b40590-7be6-4c8a-9ea9-ced8e8543905)
![image](https://github.com/MoojMidge/service.upnext/assets/143577835/fca2eb38-071d-434b-9486-ca89bd44e64f)

**Comment by MoojMidge** [comment]
No idea. 

If you can provide a debug log then that may provide some information
https://kodi.wiki/view/Log_file/Easy

**Comment by Lefo16** [comment]
[kodi.log](https://github.com/MoojMidge/service.upnext/files/12481400/kodi.log)

Here you go :)

TIA

**Comment by MoojMidge** [comment]
Have you added anything to your Kodi library?

The widgets only query information from the local Kodi video library for speed, so unless you enable library integration for the video plugins you use (I know you can do this using TMDb Helper, not sure about other plugins), the UpNext widgets won't have anything to show.

**Comment by Lefo16** [comment]
![image](https://github.com/MoojMidge/service.upnext/assets/143577835/df656cec-dbff-4a5c-ae92-bdfde5d2e0f0)
Tried Library Integration for TMDB Helper and seems to not working. See above setting. Am I missing something?

**Comment by MoojMidge** [comment]
You will still need to add items (manually via context menu) or lists (via the "Auto-update library from Trakt list(s)" option in your screenshot above) to your library and also ensure that those items are scanned into your library.

TMDB Helper is pretty handy but it can't read your mind to tell what you want in your library 😉

**Comment by MoojMidge** [comment]
Closing this - the widgets pull info from a local Kodi library, when you add things to the library they will start working.
