### ISSUE TITLE
Seeing a quick Up Next popup on screen when I let playback stop due to check if still watching / auto played in a row and playback not selected

### ISSUE THREAD

**Issue by booyakafoo** [MoojMidge/service.upnext#31]
Have check if still watching enabled, after 3 videos automatically played.  If I let the playback stop on it's own by not pressing anything in the Up Next popup.  Playback will stop OK, but there will be a quick Up Next popup that happens shortly after playback.  Also the Auto played in a row will be 1 shorter than the value selected in the settings if I play something from the same show again.  2 of 3 rather than 3 of 3 before the "continue watching" pop up will show.  It appears after stopping playback there is a video check that happens in the background which triggers the popup and updates the playback counter value.  Debugs below.  This was happening before the recent #30 fix also.  Thanks

https://paste.kodi.tv/hiniyenoda.kodi

**Comment by MoojMidge** [comment]
Yeah that is a bit strange. The order of the stop and playback events is all messed up.

That's also why you get an error in `plugin.service.mqtt/service.py` - it doesn't expect the playback announcement and `onAVStarted` callback to trigger when playback has already stopped and there is no active player.

Will have to think about the best way to handle this.

**Comment by booyakafoo** [comment]
Do you suspect it is something with my setup or something different in how Kodi 21 operates?  Thanks for looking into it.

**Comment by MoojMidge** [comment]
It's nothing specific to your setup or new with Kodi 21. It has been an issue with Kodi for a while, and there are checks in this plugin to handle the oddness (hence why it doesn't raise an exception like what happens with `plugin.service.mqtt`).

However as the development of the plugin progressed, I have side stepped some of those checks in the interest of improving speed, which results in the underlying Kodi issue presenting itself in this manner.

See if this commit fixes it:
https://github.com/MoojMidge/service.upnext/commit/6aaf633a27468297a1b2c30886abfd358d3d2da6

Available in new release:
https://github.com/MoojMidge/service.upnext/releases/tag/v2.0.28%2Bdev.0

**Comment by booyakafoo** [comment]
I installed service.upnext-2.0.28+matrix.dev.0.zip

I'm having a separate issue with this release.  Occasionally when I reach the end of unattended playback (1/1 for my test debug).  I get kicked back to the skin but playback of the next episode starts and continues in the background of the skin.

![Clipped_image_20240523_114639](https://github.com/MoojMidge/service.upnext/assets/3913228/f02b0694-6603-477f-85e9-63ab0f7686e9)

https://paste.kodi.tv/elicidalar.kodi
https://paste.kodi.tv/sisuninaqo.kodi

**Comment by MoojMidge** [comment]
Not a lot can be done about that. Try this and see if it helps
https://github.com/MoojMidge/service.upnext/issues/9#issuecomment-1666585506

**Comment by booyakafoo** [comment]
Yes.  The still watching popup showed as it should.  For testing I changed the still watching setting to 1 from 3, but was happening with the setting set to 3 also.  
I didn't press anything and video playback should have stopped, but the next video started in the background.

**Comment by MoojMidge** [comment]
OK, I'll have to see if anything can be done. Can you open a separate issue so I don't forget?

**Comment by booyakafoo** [comment]
Definitely.  Thanks again for all the help!
