### ISSUE TITLE
how do you install this fork on kodi? 

### ISSUE THREAD

**Issue by peter-mogaka** [MoojMidge/service.upnext#32]
I tried installing this fork using the add source method, install from repo and install from zip file method but they all dont seem to work.

Source is added successfully but not files are avialble for install.
I´m running the latest version of kodi

Please provide some guidance.

**Comment by MoojMidge** [comment]
This addon is not in any source or repository accessible through Kodi, so those methods won't work.

https://github.com/MoojMidge/service.upnext/releases/tag/v2.0.27%2Bdev.0 is the latest release. Downloading it and installing from zip should work without issue. If it didn't, then you need to be more specific with what steps you tried and what errors occurred.

**Comment by peter-mogaka** [comment]
i only tried the repo method on kodi, both install fro repo and zip. I havent downloaded it yet. will try and get back to you
