### ISSUE TITLE
Start episodes from the  Episodes In-Progesss or Your next Episode trakt list issues

### ISSUE THREAD

**Issue by Prophiii** [MoojMidge/service.upnext#35]
Hello and thanks for the great work so far.

I'm currently stuck and that's why I'm asking here.

I have the latest version of Up Next from here and I'm using the current Tmdb helper from jurialmunkey.

Up Next works basically great for me, except in the case where, if I start an episode from the "episode in progress" widget, I don't see an Up Next popup. In an older version, this popup was displayed, but the next episode did not start. Could it be that it doesn't find the next episode in the Trakt "in progress" or "your next episode" lists?

I hope the problem can be solved, otherwise I'll have to fall back on the season when using the Continue Watching widget.

Thanks in advance!

**Comment by Prophiii** [comment]
I have now set the player to the playlist on upnext. It does show the popup at the end of the episode, but nothing happens when I click it. the popup window just disappears.

**Comment by MoojMidge** [comment]
Will need a debug log to be able to check what may be happening

https://kodi.wiki/view/Log_file/Easy

**Comment by MoojMidge** [comment]
Closed. No response by OP.
