### ISSUE TITLE
Next episode marked as watched after stopping

### ISSUE THREAD

**Issue by MoojMidge** [MoojMidge/service.upnext#36]
I just noticed that when pressing play, the next episode starts successfully, however, once I paused and stopped the episode after only a couple of seconds, I noticed that this is getting marked as watched. This should not occur.

Thanks

_Originally posted by @vella9 in https://github.com/MoojMidge/service.upnext/issues/33#issuecomment-2282799061_

**Comment by MoojMidge** [comment]
`Settings > Behaviour > Playback > Mark as watched` by default is set to `Forced on`. If you change it to `Disabled` does the same thing happen?

Can you get a log of this?

**Comment by vella9** [comment]
> If you change it to `Disabled` does the same thing happen?

yes, same thing happened.

[kodi.log](https://github.com/user-attachments/files/16575375/kodi.log)

**Comment by MoojMidge** [comment]
> yes, same thing happened.

If that is the case, then it is probably nothing to do with UpNext. Does the same thing happen to the first video, if you stop it shortly after starting playback?

For this type of issue, will specifically need a debug log to try and figure out what is happening:
https://kodi.wiki/view/Log_file/Easy

**Comment by vella9** [comment]
> Does the same thing happen to the first video, if you stop it shortly after starting playback?

No, this does not get marked as watched.

Tbh, exactly after changing `Settings > Behaviour > Playback > Mark as watched` to `Disabled`, it worked fine for a couple to tests on new shows (shows that I did not test on before changing the setting to `Disabled`). But right after I tested using a show that had this issue, it occurred again.

> For this type of issue, will specifically need a debug log to try and figure out what is happening:

Is this what you are looking for?

[kodi.zip](https://github.com/user-attachments/files/16575607/kodi.zip)

**Comment by MoojMidge** [comment]
> it worked fine for a couple to tests on new shows (shows that I did not test on before changing the setting to `Disabled`)

Is this in your log? If so, what shows were they? Can you check these with the setting set to `Forced on`?

> But right after I tested using a show that had this issue, it occurred again.

Is this in the log? If so, what show was it?

> Is this what you are looking for?

Not quite, but lets hold off on additional logs for the moment, need to understand what is being shown in the current logs first.

> So I think, this has to do with UpNext.

Maybe. Can you check with the Trakt plugin disabled?

**Comment by vella9** [comment]
> Is this in your log? If so, what shows were they? 

No, these are not in the log, and I cannot replicate it now.

**Comment by vella9** [comment]
> Can you check with the Trakt plugin disabled?

I will try later on

**Comment by vella9** [comment]
> Can you check with the Trakt plugin disabled?

I disabled the Trakt addon, but the same issue occurred. Second episode still got marked as watched after a couple of seconds.

**Comment by MoojMidge** [comment]
> Tested using `Forced on` and issue occurred on TV Shows The Tattooist of Auschwitz and The OA

Was this in your log? With forced on, the next episode that only plays for a short time is getting marked as watched? And this doesn't work correctly, consistently? 

> Tested using `Disabled ` on TV Show The Walking Dead: Daryl Dixon (never tested on this before) and issue did not occur. I stopped episode 2 after a couple of seconds and it was not marked as watched, as it should be.

This also works correctly, consistently? 

The problem is that the functionality in UpNext to force watched only works on library content, and I haven't seen it actually be used in the logs.

There was a signal sent to the Trakt addon in the logs, but this doesn't have any actual episode information (and therefore should not be sent), which I thought may be causing the Trakt addon to get confused and incorrectly scrobble the wrong episode. 

I'll have to have a closer look a bit later, but at first glance nothing looks amiss from UpNext.

**Comment by vella9** [comment]
> Was this in your log? With forced on, the next episode that only plays for a short time is getting marked as watched? And this doesn't work correctly, consistently?

Yes and Yes. I tried it on those 2 TV Shows and both had the same issue yes.



> This also works correctly, consistently?

I only tried this on 1 TV show.

I will try to test further today and let you know.

**Comment by MoojMidge** [comment]
> So, this time, I did not manage to replicate the scenario where I started episode 2 but this was not marked as watched.

Yeah, that's what I suspected - it was just a coincidence that it appeared to be working correctly previously, so this is still relevant:


> The problem is that the functionality in UpNext to force watched only works on library content, and I haven't seen it actually be used in the logs.
> 
> There was a signal sent to the Trakt addon in the logs, but this doesn't have any actual episode information (and therefore should not be sent), which I thought may be causing the Trakt addon to get confused and incorrectly scrobble the wrong episode.
> 
> I'll have to have a closer look a bit later, but at first glance nothing looks amiss from UpNext.

Latest master disables the unnecessary signal sent to the Trakt addon. Can you see if that has any effect?

https://github.com/MoojMidge/service.upnext/archive/refs/heads/master.zip

**Comment by vella9** [comment]
> https://github.com/MoojMidge/service.upnext/archive/refs/heads/master.zip

Hi @MoojMidge, unfortunately, it is still occuring

**Comment by MoojMidge** [comment]
Yeah didn't that would fix it, but I don't think it is actually directly related to this plugin.

Will need a full debug log. You can follow the instructions at https://kodi.wiki/view/Log_file/Easy to produce it.

**Comment by vella9** [comment]
Log attached. I only tried once with the TV Show The Acolyte from episode 1 to episode 2. Thanks @MoojMidge 

[kodi.log](https://github.com/user-attachments/files/16644357/kodi.log)

**Comment by MoojMidge** [comment]
Where exactly are you seeing the second episode displayed as watched?

UpNext can only do the following:
- Mark an item in the Kodi database as watched
- Provide a signal for the Trakt addon to mark something as watched in Trakt

Neither of these things are occuring, and the log shows the first episode getting marked as watched in the Kodi database, and the second episode not getting marked as watched. Both videos have their resume time saved.

I suspect the video addon you are using is marking the video as watched when it is doing its own Trakt scrobbling, or otherwise marking the video as watched when it is building its video lists.

**Comment by vella9** [comment]
> Where exactly are you seeing the second episode displayed as watched?

The episode is getting marked as watched with the tick in the widget row I use and also on Trakt

**Comment by vella9** [comment]
This particular issue is occurring in the widgets row from the video-addon I am using. The strange reason is that this is only occurring when UpNext is used.

I also tried to use a widget, this time from TMDBHelper, and the issue was not occurring here, but the first episode is not getting marked as watched in this case.

I will try to test further with different methods. Thanks @MoojMidge
