### ISSUE TITLE
Pop up

### ISSUE THREAD

**Issue by Peter3344** [MoojMidge/service.upnext#38]
Is it possible that upnext don't pop up if episode not released

**Comment by Peter3344** [comment]
Yes am using the tmdb integration disable exact match and enabled tmdb helper settings check upnext calendar I used tvshow Emily in Paris episode 5 and episode 6 is not released yet and upnext pop up 

[Kodi log ](https://paste.kodi.tv/getusohowo.kodi)

**Comment by MoojMidge** [comment]
But have you actually enabled `Hide unaired episodes` and `Hide items without airdates` in TMDbHelper?

**Comment by Peter3344** [comment]
> But have you actually enabled `Hide unaired episodes` and `Hide items without airdates` in TMDbHelper?

I enabled it both and same issue 
Here is a log after enabling them 
[kodi log ](https://paste.kodi.tv/utigugajax.kodi)](https://paste.kodi.tv/utigugajax.kodi)

**Comment by MoojMidge** [comment]
Ok I'll have a look

**Comment by MoojMidge** [comment]
Added to latest release. No popup will be shown if next episode is unaired, regardless of the TMDbHelper settings to list them
