### ISSUE TITLE
Not marked as watched

### ISSUE THREAD

**Issue by Peter3344** [MoojMidge/service.upnext#39]
Hello am using the way of 'exact match' disabled if I play the next episode the previous one is not marked as watched 'forced watched' on btw

**Comment by MoojMidge** [comment]
If you want assistance then you will need to provide a debug log
https://kodi.wiki/view/Log_file/Easy

**Comment by Peter3344** [comment]
Here a debug log thank you 
[kodidebuglog](https://paste.kodi.tv/abekuyiwub.kodi)

**Comment by MoojMidge** [comment]
> forced watched' on

This only works for library content.

Plugin content is handled by Kodi natively (and the video in the log is being marked as watched), but the video plugin needs to handle this properly too.

If you are using Trakt to manage this externally of Kodi and the video plugin, then any issues with marking a video watched would be related to the scrobbling. The log indicates that the Trakt addon is not correctly scrobbling the actual play time and is also  not detecting the change from one video to another.

This is all outside of the control of this addon, however recent versions of this addon stopped sending Trakt a signal to indicate that playback had stopped for non-library content. Could try just sending this signal anyway, it may help, it may not do anything.

**Comment by MoojMidge** [comment]
> Could try just sending this signal anyway, it may help, it may not do anything.

https://github.com/MoojMidge/service.upnext/releases/tag/v2.0.30%2Bdev.0 will try to signal to service.trakt that the video has finished. Can try it and see if it improves anything.

**Comment by Peter3344** [comment]
Yes working great 🎉🎉🎉🎉🎉
thank you 🙏
