### ISSUE TITLE
upnext notification doesn't appear v2.0.29/v2.0.30 and Jellyfin

### ISSUE THREAD

**Issue by Pauld-1** [MoojMidge/service.upnext#40]
Hello,

After upgrading from v2.0.28 from v2.0.30, the notification doesn't appear and the next episode doesn't play. I also tried v2.0.29 with the same problem however it works again if I revert to v2.0.28.

I'll be grateful if you could have a look at the attached log please.
 
[kodi.log](https://github.com/user-attachments/files/17534540/kodi.log)

**Comment by MoojMidge** [comment]
I'm surprised this worked previously. The log shows it failing in v2.0.28 as well.

See if it works using https://github.com/MoojMidge/service.upnext/archive/refs/heads/master.zip

**Comment by Pauld-1** [comment]
working :smiley: thank you!
