### ISSUE TITLE
upnext notification doesn't appear

### ISSUE THREAD

**Issue by Peter3344** [MoojMidge/service.upnext#42]
upnext popup dosen`t appear again and i got an error

[kodi.log](https://github.com/user-attachments/files/17962442/kodi.log)

**Comment by MoojMidge** [comment]
Looks like TheMovieDB Helper was updated recently:
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/commit/b4f55b31a9e61660f03b5089203ea3f0f0e4f791

Fixed in https://github.com/MoojMidge/service.upnext/archive/refs/heads/master.zip
